---
title: "Cell chat circos plot"
author: "Paola Pibiri"
date: "2023-10-20"
output: ''
---

```{r header, include=FALSE}
###################################################################################################################
# Authors: Paola Pibiri
# Name: Cellechat_circos_plot_psc.Rmd
# Function: create the circos plot pictures for PSC project
###################################################################################################################
```



```{r libraries, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
####################
# libraries        #
####################


library(circlize)
library(reshape2)
library(dplyr)
library(nichenetr)
library(tidyverse)
library(circlize)
library(RColorBrewer)
library(ggplot2)
library(CellChat)
library(Seurat)
```



```{r functions, echo=FALSE}

# functions
init_cellchat_object <- function(seurat_object, assay = 'SCT', slot = 'data', ident = 'mergedcelltype'){
  # set the default assay
  DefaultAssay(seurat_object) <- assay
  # extract the data
  data.input <- GetAssayData(seurat_object, assay = assay, slot = slot)
  meta <- seurat_object@meta.data
  # create the object
  cellchat <- createCellChat(object = data.input, meta = meta, group.by = ident)
  return(cellchat)
}

preprocess_cellchat_object <- function(chat_object, nthreads=8){
  # set the database
  CellChatDB <- CellChatDB.human # use CellChatDB.mouse if running on mouse data
  CellChatDB.use <- CellChatDB # simply use the default CellChatDB
  chat_object@DB <- CellChatDB.use
  chat_object <- subsetData(chat_object) # This step is necessary even if using the whole database
  # set multithreading options
  future::plan("multisession", workers = nthreads) # do parallel
  # get genes
  chat_object <- identifyOverExpressedGenes(chat_object)
  chat_object <- identifyOverExpressedInteractions(chat_object)
  # project gene expression data onto PPI network (optional)
  chat_object <- projectData(chat_object, PPI.human)
  return(chat_object)
}

inference_communication_network <- function(chat_object, min.cells=10, thresh=1){
  # Compute the communication probability and infer cellular communication network
  chat_object <- computeCommunProb(chat_object)
  # Filter out the cell-cell communication if there are only few number of cells in certain cell groups
  chat_object <- filterCommunication(chat_object, min.cells = min.cells)
  # Infer the cell-cell communication at a signaling pathway level
  chat_object <- computeCommunProbPathway(chat_object, thresh = thresh)
  # Calculate the aggregated cell-cell communication network
  chat_object <- aggregateNet(chat_object, thresh = thresh)
  return(chat_object)
}

do_default_cellchat_workflow <- function(seurat_object, assay = 'SCT', slot = 'data', ident = 'celltype_final.v1', min.cells=10, nthreads=8, thresh=0.05){
  # go through the steps
  chat_object <- init_cellchat_object(seurat_object, assay = assay, slot = slot, ident = ident)
  chat_object <- preprocess_cellchat_object(chat_object, nthreads = nthreads)
  chat_object <- inference_communication_network(chat_object, min.cells = min.cells, thresh = thresh)
  return(chat_object)
}

do_default_cellchat_workflow_per_timepoint <- function(seurat_object, timepoint.column='timepoint.final', assay = 'SCT', slot = 'data', ident = 'celltype_final.v1', min.cells=10, nthreads=8, thresh=0.05){
  # save the objects in a list
  chat_per_timepoint <- list()
  # check each cell type
  for(timepoint in unique(seurat_object@meta.data[[timepoint.column]])){
    # subset to that timepoint
    seurat_timepoint <- seurat_object[, seurat_object@meta.data[[timepoint.column]] == timepoint]
    # go through the work flow
    chat_timepoint <- do_default_cellchat_workflow(seurat_timepoint, assay = assay, slot = slot, ident = ident, min.cells=min.cells, nthreads=nthreads, thresh = thresh)
    # add to list
    chat_per_timepoint[[timepoint]] <- chat_timepoint
  }
  return(chat_per_timepoint)
}


plot_communication_network <- function(chat_object){
  groupSize <- as.numeric(table(chat_object@idents))
  par(mfrow = c(1,2), xpd=TRUE)
  netVisual_circle(chat_object@net$count, vertex.weight = groupSize, weight.scale = T, label.edge= F, title.name = "Number of interactions")
  netVisual_circle(chat_object@net$weight, vertex.weight = groupSize, weight.scale = T, label.edge= F, title.name = "Interaction weights/strength")
}

plot_communication_network_separate <- function(chat_object, slot = 'weight'){
  # grab the number of groups
  groupSize <- as.numeric(table(chat_object@idents))
  # grab the right slot
  mat <- chat_object@net[[slot]]
  # make a perfect square of the plot
  par(mfrow = c(ceiling(sqrt(nrow(mat))),ceiling(sqrt(nrow(mat)))), xpd=TRUE)
  # make the plots
  for (i in 1:nrow(mat)) {
    mat2 <- matrix(0, nrow = nrow(mat), ncol = ncol(mat), dimnames = dimnames(mat))
    mat2[i, ] <- mat[i, ]
    netVisual_circle(mat2, vertex.weight = groupSize, weight.scale = T, edge.weight.max = max(mat), title.name = rownames(mat)[i], arrow.size=0.005)
  }
  par(mfrow=c(1,1))
}

plot_all_communications_networks_separate <- function(chat_object_per_timepoint_and_chem, output_loc='', file_type='pdf', chems=c('V2', 'V3'), width=10, height=10, slot = 'weight'){
  # plot each timepoint
  for(timepoint in names(chat_object_per_timepoint_and_chem[[chems[[1]]]])){
    # plot each chem
    for(chem in chems){
      # paste the full output loc
      output_loc_full <- paste(output_loc, 'communications_separate_', timepoint, '_', chem, '_', slot, '.', file_type, sep = '')
      print(output_loc_full)
      # init where we will save
      if(file_type == 'pdf'){
        pdf(output_loc_full, width = width, height = height)
      }
      else if(file_type == 'png'){
        png(output_loc_full, width = width, height = height)
      }
      else{
        print('unknown file type, doing pdf instead')
        pdf(output_loc_full, width = width, height = height)
      }
      try({
        # grab the number of groups
        groupSize <- as.numeric(table(chat_object_per_timepoint_and_chem[[chem]][[timepoint]]@idents))
        # grab the right slot
        mat <- chat_object_per_timepoint_and_chem[[chem]][[timepoint]]@net[[slot]]
        # make a perfect square of the plot
        par(mfrow = c(ceiling(sqrt(nrow(mat))),ceiling(sqrt(nrow(mat)))), xpd=TRUE)
        # make the plots
        for (i in 1:nrow(mat)) {
          mat2 <- matrix(0, nrow = nrow(mat), ncol = ncol(mat), dimnames = dimnames(mat))
          mat2[i, ] <- mat[i, ]
          netVisual_circle(mat2, vertex.weight = groupSize, weight.scale = T, edge.weight.max = max(mat), title.name = paste(rownames(mat)[i], 'in', chem, timepoint))
        }
      })
      dev.off()
    }
  }
  par(mfrow=c(1,1))
}

plot_all_communications_networks <- function(chat_object_per_timepoint_and_chem, output_loc='', file_type='pdf', chems=c('V2', 'V3'), width=10, height=10){
  # plot each timepoint
  for(timepoint in names(chat_object_per_timepoint_and_chem[[chems[[1]]]])){
    # paste the full output loc
    output_loc_full <- paste(output_loc, 'communications_', timepoint, '.', file_type, sep = '')
    print(output_loc_full)
    # init where we will save
    if(file_type == 'pdf'){
      pdf(output_loc_full, width = width, height = height)
    }
    else if(file_type == 'png'){
      png(output_loc_full, width = width, height = height)
    }
    else{
      print('unknown file type, doing pdf instead')
      pdf(output_loc_full, width = width, height = height)
    }
    try({
      # plot each chem
      for(chem in chems){
        groupSize <- as.numeric(table(chat_object_per_timepoint_and_chem[[chem]][[timepoint]]@idents))
        netVisual_circle(chat_object_per_timepoint_and_chem[[chem]][[timepoint]]@net$count, vertex.weight = groupSize, weight.scale = T, label.edge= F, title.name = paste("Number of interactions", 'in', chem, timepoint))
        netVisual_circle(chat_object_per_timepoint_and_chem[[chem]][[timepoint]]@net$weight, vertex.weight = groupSize, weight.scale = T, label.edge= F, title.name = paste("Interaction weights/strength", 'in', chem, timepoint))
      }
    })
    dev.off()
  }
}

plot_all_aggregate_pathways <- function(chat_object_per_timepoint_and_chem, output_loc='', file_type='pdf', chems=c('V2', 'V3'), width=10, height=10){
  # plot each timepoint
  for(timepoint in names(chat_object_per_timepoint_and_chem[[chems[[1]]]])){
    # plot each chem
    for(chem in chems){
      # paste the full output loc
      output_loc_full <- paste(output_loc, 'pathways_', timepoint, '_', chem, '.', file_type, sep = '')
      print(output_loc_full)
      # init where we will save
      if(file_type == 'pdf'){
        pdf(output_loc_full, width = width, height = height)
      }
      else if(file_type == 'png'){
        png(output_loc_full, width = width, height = height)
      }
      else{
        print('unknown file type, doing pdf instead')
        pdf(output_loc_full, width = width, height = height)
      }
      try({
        par(mfrow=c(3,2))
        for(pathway in chat_object_per_timepoint_and_chem[[chem]][[timepoint]]@netP$pathways){
          netVisual_aggregate(chat_object_per_timepoint_and_chem[[chem]][[timepoint]], signaling = c(pathway), layout = "circle")
        }
      })
      dev.off()
    }
  }
}

compare_conditions <- function(all_conditions_list, condition.1, condition.2){
  # subset to only the conditions we want
  conditions.list <- list(condition.1 = all_conditions_list[[condition.1]], condition.2 = all_conditions_list[[condition.2]])
  conditions <- mergeCellChat(conditions.list, add.names = names(conditions.list))
  # compare interactions and strength numbers
  gg1 <- compareInteractions(conditions, show.legend = F, group = c(1,2))
  gg2 <- compareInteractions(conditions, show.legend = F, group = c(1,2), measure = "weight")
  # check strengths and weights as circle plots
  #gg3 <- plot(netVisual_diffInteraction(conditions, weight.scale = T))
  #gg4 <- plot(netVisual_diffInteraction(conditions, weight.scale = T, measure = "weight"))
  # check strengths and weights as heatmaps
  gg5 <- netVisual_heatmap(conditions)
  gg6 <- netVisual_heatmap(conditions, measure = "weight")
  # compute net neutrality score to show differences
  conditions.list[[1]] <- netAnalysis_computeCentrality(conditions.list[[1]])
  conditions.list[[2]] <- netAnalysis_computeCentrality(conditions.list[[2]])
  # visualize in 2d space, #first get the number of links in both sets
  conditions.list.num.link <- sapply(conditions.list, function(x) {rowSums(x@net$count) + colSums(x@net$count)-diag(x@net$count)})
  # set a max and min, so the plots will have the same scale
  conditions.list.weight.MinMax <- c(min(conditions.list.num.link), max(conditions.list.num.link))
  # make the plots
  gg7 <- netAnalysis_signalingRole_scatter(conditions.list[[1]], title = names(conditions.list)[1], weight.MinMax = conditions.list.weight.MinMax)
  gg8 <- netAnalysis_signalingRole_scatter(conditions.list[[2]], title = names(conditions.list)[2], weight.MinMax = conditions.list.weight.MinMax)
  # identify signalling groups based on structure similarity
  conditions <- computeNetSimilarityPairwise(conditions, type = "functional")
  # Compute signaling network similarity for datasets 1 2
  conditions <- netEmbedding(conditions, type = "functional")
  # Manifold learning of the signaling networks for datasets 1 2
  conditions <- netClustering(conditions, type = "functional")
  # Visualization in 2D-space
  gg9 <- netVisual_embeddingPairwise(conditions, type = "functional", label.size = 3.5)
  # same, but on structure similarity this time
  conditions <- computeNetSimilarityPairwise(conditions, type = "structural")
  conditions <- netEmbedding(conditions, type = "structural")
  conditions <- netClustering(conditions, type = "structural")
  gg10 <- netVisual_embeddingPairwise(conditions, type = "structural", label.size = 3.5)
  # put everything in a nice list
  all_plots <- list('interactions_number' = gg1,
                    'interactions_weight' = gg2,
                    #'circle_number' = gg3,
                    #'circle_weight' = gg4,
                    'heatmap_number' = gg5,
                    'heatmap_weight' = gg6,
                    'scatter_cond1' = gg7,
                    'scatter_cond2' = gg8,
                    'clust_functional' = gg9,
                    'clust_structural' = gg10)
  return(all_plots)
}

do_compare_conditions <- function(all_conditions_list, condition.1, condition.2){
  # subset to only the conditions we want
  conditions.list <- list(condition.1 = all_conditions_list[[condition.1]], condition.2 = all_conditions_list[[condition.2]])
  conditions <- mergeCellChat(conditions.list, add.names = names(conditions.list))
  # compute net neutrality score to show differences
  conditions.list[[1]] <- netAnalysis_computeCentrality(conditions.list[[1]])
  conditions.list[[2]] <- netAnalysis_computeCentrality(conditions.list[[2]])
  # identify signalling groups based on structure similarity
  conditions <- computeNetSimilarityPairwise(conditions, type = "functional")
  # Compute signaling network similarity for datasets 1 2
  conditions <- netEmbedding(conditions, type = "functional")
  # Manifold learning of the signaling networks for datasets 1 2
  conditions <- netClustering(conditions, type = "functional")
  # Visualization in 2D-space
  conditions <- computeNetSimilarityPairwise(conditions, type = "structural")
  conditions <- netEmbedding(conditions, type = "structural")
  conditions <- netClustering(conditions, type = "structural")
  return(conditions)
}

chat_result_to_plots <-function(chat_plots, output_loc){
  # setup the output
  pdf(output_loc)
  #par(mfrow = c(1,2))
  #chat_plots[['circle_number']]
  #chat_plots[['circle_weight']]
  print(
    ggarrange(
      plotlist = list(
        chat_plots[['interactions_number']], 
        chat_plots[['interactions_weight']] 
      ), ncol = 1, nrow = 2
    )
  )
  print(chat_plots[['heatmap_number']] + chat_plots[['heatmap_weight']])
  print(
    ggarrange(
      plotlist = list(
        chat_plots[['scatter_cond1']], 
        chat_plots[['scatter_cond2']], 
        chat_plots[['clust_functional']], 
        chat_plots[['clust_structural']]
      ), ncol = 2, nrow = 2
    )
  )
  dev.off()
  # back to default
}

```


```{r main code}


#list.receivers <- c('Tregs', 'Inflammatory_Fibroblasts', 'CD8pos_IL17pos', 'CD4pos_PD1pos')

list.relevant.genes <- c('HLA-DRA', 'HLA-DRA', 'HLA-DRB1', 'HLA-DPA1', 'HLA-DPB1', 
                         'HLA-DQA1', 'HLA-DMA', 'HLA-DMB', 'HLA-DQB1', 'HLA-DQA2',
                         'HLA-DRB5')

list.senders <-  c('DUOX2_enterocytes', 'Inflammatory_Monocytes')

#list.excluded <- c('HLA-A','HLA-B', 'HLA-C', 'HLA-E', 'HLA-F')


# set input directory
psc.dir <- '/groups/umcg-weersma/tmp01/projects/PSC/ongoing/cellchat_circos_plot/Input_cellchat/PSC_I'
uc.dir <- '/groups/umcg-weersma/tmp01/projects/PSC/ongoing/cellchat_circos_plot/Input_cellchat/UC_I/'

# read the PSC I files 
psc_i_duox2 <- read.table(paste0(psc.dir, 'PSC_I_cellchat_DUXO2(sender).xlsx - Sheet1.tsv'), sep='\t', header=T)
psc_i_inf_mono <- read.table(paste0(psc.dir, 'PSC_I_cellchat_inflammatory_monocytes(sender).xlsx - Sheet1.tsv'), sep='\t', header=T)

#read the UC I files 
uc_i_duox2 <- read.table(paste0(uc.dir, 'UC_I_cellchat_DUXO2(sender).xlsx - Sheet1.tsv'), sep='\t', header=T)
uc_i_inf_mono <- read.table(paste0(uc.dir, 'UC_I_cellchat_inflammatory_monocytes(sender).xlsx - Sheet1.tsv'), sep='\t', header=T)


# merge the two files per condition together
merged.psc.inflamed <- rbind(psc_i_duox2, psc_i_inf_mono)
#
merged.uc.inflamed <- rbind(uc_i_duox2, uc_i_inf_mono)

#filter the two df for only the relevant genes that we want to show in the circos plot
merged.psc.inflamed <- merged.psc.inflamed %>%
  filter(ligand %in% list.relevant.genes & !(target %in% list.senders))

merged.uc.inflamed <- merged.uc.inflamed %>%
  filter(ligand %in% list.relevant.genes & !(target %in% list.senders))

# filter for only relevant columns

psc.inflamed.filtered <- merged.psc.inflamed %>%
  dplyr::select(source, target, ligand, receptor) 
  

uc.inflamed.filtered <- merged.uc.inflamed %>%
  dplyr::select(source, target, ligand, receptor) 



# rename the columns 
colnames(psc.inflamed.filtered) <- c('sender', 'receiver', 'ligand', 'receptor')
#
colnames(uc.inflamed.filtered) <- c('sender', 'receiver', 'ligand', 'receptor')


# create the extra column necessary for the circos plot 
psc.inflamed.filtered$prioritization_score <- 0.5
#
uc.inflamed.filtered$prioritization_score <- 0.5




# create new columns necessary for the code in psc inflamed
psc.inflamed.filtered$ligand_receptor <- paste(psc.inflamed.filtered$ligand, psc.inflamed.filtered$receptor, sep = "--")
psc.inflamed.filtered$niche <- paste(psc.inflamed.filtered$sender, "niche", sep = "_")
psc.inflamed.filtered$prioritization_score <- as.numeric(psc.inflamed.filtered$prioritization_score)
psc.inflamed.filtered$top_niche <- paste(psc.inflamed.filtered$sender, "niche", sep = "_")

# create new columns necessary for the code in uc inflamed
uc.inflamed.filtered$ligand_receptor <- paste(uc.inflamed.filtered$ligand, uc.inflamed.filtered$receptor, sep = "--")
uc.inflamed.filtered$niche <- paste(uc.inflamed.filtered$sender, "niche", sep = "_")
uc.inflamed.filtered$prioritization_score <- as.numeric(uc.inflamed.filtered$prioritization_score)
uc.inflamed.filtered$top_niche <- paste(uc.inflamed.filtered$sender, "niche", sep = "_")


# define the columns in PSC inflamed sender cells 


colors_PSCI_receiver = brewer.pal(n = psc.inflamed.filtered$receiver %>% unique() %>% sort() %>% length(), name = 'Pastel1') %>% magrittr::set_names(psc.inflamed.filtered$receiver %>% unique() %>% sort())

'#FBB4AE'
'#FED9A6'
'#B3CDE3'
'#FFFFCC'
'#CCEBC5'
'#E5D8BD'
'#DECBE4'

colors_PSCI_sender = c("#B2ABD2", "#F1B6DA")  %>% magrittr::set_names(psc.inflamed.filtered$sender %>% unique() %>% sort())


colors_UCI_sender = c("#B2ABD2", "#F1B6DA")  %>% magrittr::set_names(uc.inflamed.filtered$sender %>% unique() %>% sort())

'#FBB4AE'
'#FED9A6'
'#B3CDE3'
'#FFFFCC'
'#CCEBC5'
'#E5D8BD'
'#DECBE4'

colors_UCI_receiver = c('#FBB4AE','#CCEBC5', '#DECBE4', '#FED9A6', '#FFFFCC')  %>% magrittr::set_names(uc.inflamed.filtered$receiver %>% unique() %>% sort())




# some receptors are also ligands and vice versa
uc.inflamed.filtered.lr.overlap <- intersect(uc.inflamed.filtered$ligand, uc.inflamed.filtered$receptor)
# rename these
uc.inflamed.filtered[uc.inflamed.filtered$receptor %in% uc.inflamed.filtered.lr.overlap, 'receptor'] <- paste(uc.inflamed.filtered[uc.inflamed.filtered$receptor %in% uc.inflamed.filtered.lr.overlap, 'receptor'], '(as R)')
uc.inflamed.filtered[uc.inflamed.filtered$ligand %in% uc.inflamed.filtered.lr.overlap, 'ligand'] <- paste(uc.inflamed.filtered[uc.inflamed.filtered$ligand %in% uc.inflamed.filtered.lr.overlap, 'ligand'], '(as L)')

#par(mar = c(1, 1, 1, 1))






```

```{r add inf fibroblasts}
# run psc circos plot
circos_PSCI_output = make_circos_lr(psc.inflamed.filtered, colors_PSCI_sender, colors_PSCI_receiver, transparency = 0.3, scale = 0.1)


```



```{r add inf fibroblasts}
# run uc circos plot
circos_UCI_output = make_circos_lr(uc.inflamed.filtered, colors_UCI_sender, colors_UCI_receiver, transparency = 0.3, scale = 0.1)


```

```{r unique circos plot main code}

list.relevant.genes <- c('HLA-DRA', 'HLA-DRA', 'HLA-DRB1', 'HLA-DPA1', 'HLA-DPB1', 
                         'HLA-DQA1', 'HLA-DMA', 'HLA-DMB', 'HLA-DQB1', 'HLA-DQA2',
                         'HLA-DRB5')

list.senders <-  c('DUOX2_enterocytes', 'Inflammatory_Monocytes')


# set input directory
psc.dir <- '/groups/umcg-weersma/tmp01/projects/PSC/ongoing/cellchat_circos_plot/RNA_assay/input_cellranger_RNA_assay/PSC_I/'
uc.dir <- '/groups/umcg-weersma/tmp01/projects/PSC/ongoing/cellchat_circos_plot/RNA_assay/input_cellranger_RNA_assay/UC_I/'

# read the PSC I files 
psc_i_duox2 <- read.table(paste0(psc.dir, 'PSC_I_duox2.tsv'), sep='\t', header=T)
psc_i_inf_mono <- read.table(paste0(psc.dir, 'PSC_I_inflammatory_monocytes.tsv'), sep='\t', header=T)

#read the UC I files 
uc_i_duox2 <- read.table(paste0(uc.dir, 'UC_I_duox2.tsv'), sep='\t', header=T)
uc_i_inf_mono <- read.table(paste0(uc.dir, 'UC_I_inflammatory_monocytes.tsv'), sep='\t', header=T)


# merge the two files per condition together
merged.psc.inflamed <- rbind(psc_i_duox2, psc_i_inf_mono)
#
merged.uc.inflamed <- rbind(uc_i_duox2, uc_i_inf_mono)


#filter the two df for only the relevant genes that we want to show in the circos plot
merged.psc.inflamed <- merged.psc.inflamed %>%
  filter(ligand %in% list.relevant.genes & !(target %in% list.senders))

merged.uc.inflamed <- merged.uc.inflamed %>%
  filter(ligand %in% list.relevant.genes & !(target %in% list.senders))


# filter for only relevant columns
psc.inflamed.filtered <- merged.psc.inflamed %>%
  dplyr::select(source, target, ligand, receptor) 
  

uc.inflamed.filtered <- merged.uc.inflamed %>%
  dplyr::select(source, target, ligand, receptor) 



# rename the columns 
colnames(psc.inflamed.filtered) <- c('sender', 'receiver', 'ligand', 'receptor')
#
colnames(uc.inflamed.filtered) <- c('sender', 'receiver', 'ligand', 'receptor')


# find the rows that are the same between UC and PSC
same.psc.uc <- inner_join(psc.inflamed.filtered, uc.inflamed.filtered)
# add one column to define that these rows are present in both
same.psc.uc$state <- 'PSC and UC'

# create a unique dataframe for UC and PSC keeping track of what is in PSC, what in UC, and what is in both
diff.uc.inflamed <- dplyr::setdiff(uc.inflamed.filtered,psc.inflamed.filtered)
diff.psc.inflamed <- dplyr::setdiff(psc.inflamed.filtered, uc.inflamed.filtered)
# add one column to specify that these are unique for PSC and UC 
diff.uc.inflamed$state <- 'UC'
diff.psc.inflamed$state <- 'PSC'

#rbind the 3 df all together keeping information about what is unique 
final.merged <- rbind(same.psc.uc, diff.psc.inflamed, diff.uc.inflamed)

# create the extra column necessary for the circos plot 
final.merged$prioritization_score <- 0.5

# create new columns necessary for the code in psc inflamed
final.merged$ligand_receptor <- paste(final.merged$ligand, final.merged$receptor, sep = "--")
final.merged$niche <- paste(final.merged$sender, "niche", sep = "_")
final.merged$prioritization_score <- as.numeric(final.merged$prioritization_score)
final.merged$top_niche <- paste(final.merged$sender, "niche", sep = "_")


# define the colors  
colors_sender = c("#B2ABD2", "#F1B6DA")  %>% magrittr::set_names(final.merged$sender %>% unique() %>% sort())

colors_receiver = c('#FBB4AE','#B3CDE3', '#CCEBC5', '#DECBE4', '#FED9A6', '#FFFFCC')  %>% magrittr::set_names(final.merged$receiver %>% unique() %>% sort())

dir.out <- '/groups/umcg-weersma/tmp01/projects/PSC/ongoing/cellchat_circos_plot/RNA_assay/PSC_UC/'

```

```{r unique circos plot}

circos_output = make_circos_lr(final.merged, colors_sender, colors_receiver, transparency = 0.3, scale = 0.1)

```


```{r unique singals psc main code}

psc.unique <- diff.psc.inflamed
#
psc.unique$prioritization_score <- 0.5

# create new columns necessary for the code in psc inflamed
psc.unique$ligand_receptor <- paste(psc.unique$ligand, psc.unique$receptor, sep = "--")
psc.unique$niche <- paste(psc.unique$sender, "niche", sep = "_")
psc.unique$prioritization_score <- as.numeric(psc.unique$prioritization_score)
psc.unique$top_niche <- paste(psc.unique$sender, "niche", sep = "_")

# define the colors  
colors.psc.unique.sender = c("#B2ABD2", "#F1B6DA")  %>% magrittr::set_names(psc.unique$sender %>% unique() %>% sort())

colors.psc.unique.receiver = c('#B3CDE3')  %>% magrittr::set_names(psc.unique$receiver %>% unique() %>% sort())

dir.out <- '/groups/umcg-weersma/tmp01/projects/PSC/ongoing/cellchat_circos_plot/RNA_assay/PSC_unique/'

```


```{r psc unique}

circos.psc.unique <- make_circos_lr(psc.unique, colors.psc.unique.sender, colors.psc.unique.receiver, transparency = 0.3, scale = 0.1)


```


```{r unique singals uc main code}

uc.unique <- diff.uc.inflamed
#
uc.unique$prioritization_score <- 0.5

# create new columns necessary for the code in uc inflamed
uc.unique$ligand_receptor <- paste(uc.unique$ligand, uc.unique$receptor, sep = "--")
uc.unique$niche <- paste(uc.unique$sender, "niche", sep = "_")
uc.unique$prioritization_score <- as.numeric(uc.unique$prioritization_score)
uc.unique$top_niche <- paste(uc.unique$sender, "niche", sep = "_")

# define the colors  
colors.uc.unique.sender = c("#B2ABD2", "#F1B6DA")  %>% magrittr::set_names(uc.unique$sender %>% unique() %>% sort())

colors.uc.unique.receiver = c('#FBB4AE','#CCEBC5', '#DECBE4', '#FED9A6', '#FFFFCC')  %>% magrittr::set_names(uc.unique$receiver %>% unique() %>% sort())

dir.out <- '/groups/umcg-weersma/tmp01/projects/PSC/ongoing/cellchat_circos_plot/RNA_assay/UC_unique/'

```


```{r uc unique}

circos.uc.unique <- make_circos_lr(uc.unique, colors.psc.unique.sender, colors.uc.unique.receiver, transparency = 0.3, scale = 0.1)


```

```{r common singals main code}

common.signals <- same.psc.uc
#
common.signals$prioritization_score <- 0.5

# create new columns necessary for the code in uc inflamed
common.signals$ligand_receptor <- paste(common.signals$ligand, common.signals$receptor, sep = "--")
common.signals$niche <- paste(common.signals$sender, "niche", sep = "_")
common.signals$prioritization_score <- as.numeric(common.signals$prioritization_score)
common.signals$top_niche <- paste(common.signals$sender, "niche", sep = "_")

# define the colors  
common.signals.sender = c("#B2ABD2", "#F1B6DA")  %>% magrittr::set_names(common.signals$sender %>% unique() %>% sort())

common.signals.receiver = c('#FBB4AE','#CCEBC5', '#DECBE4', '#FED9A6', '#FFFFCC')  %>% magrittr::set_names(common.signals$receiver %>% unique() %>% sort())

dir.out <- '/groups/umcg-weersma/tmp01/projects/PSC/ongoing/cellchat_circos_plot/original_cells/common_signals/'

```


```{r common}

circos.common <- make_circos_lr(common.signals, common.signals.sender, common.signals.receiver, transparency = 0.3, scale = 0.1)


```



